import '@testing-library/jest-dom'
import { afterEach, beforeAll, afterAll } from 'vitest'
import { cleanup } from '@testing-library/react'
import { server } from './handlers/auth.handlers'
import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

if (!i18n.isInitialized) {
  i18n.use(initReactI18next).init({
    lng: 'en',
    fallbackLng: 'en',
    resources: {
      en: {
        translation: {
          nav: { home: 'Home', charts: 'Charts', yatras: 'Yatras', settings: 'Settings' },
          yatras: {
            createNewYatra: 'Create new yatra',
            shareInvite: 'Share invite link',
            copyInvite: 'Copy invite link',
            inviteCopied: 'Invite link copied!',
            sectionInvite: 'Invite',
            sectionGeneral: 'General',
            sectionPractices: 'Practices',
            sectionMembers: 'Members',
            adminSettings: 'Admin settings',
            yatraName: 'Yatra name',
            showStability: 'Show stability metrics',
            stabilityDesc: 'Show heatmap and trend arrows for each member\'s practice consistency.',
            addNewPractice: 'Add new practice',
            noMembers: 'No members yet',
            admin: 'Admin',
            removeMember: 'Remove',
            removeMemberTitle: 'Remove member?',
            removeMemberMsg: 'Remove {{name}} from the yatra?',
            deletePracticeTitle: 'Delete practice?',
            deletePracticeMsg: 'Delete "{{name}}"? This cannot be undone.',
            deleteYatra: 'Delete yatra',
            deleteYatraTitle: 'Delete yatra?',
            deleteYatraMsg: 'This will permanently delete the yatra and all its data. This cannot be undone.',
            visibleTo: 'Visible to',
            adminsOnly: 'Admins only',
            everyone: 'Everyone',
            statLabel: 'Label',
            statPractice: 'Practice',
            statAggregation: 'Aggregation',
            statTimeRange: 'Time range',
            addStatistic: 'Add statistic',
            selectPractice: 'Select practice…',
            statLabelPlaceholder: 'e.g. Average meditation time',
            statistics: 'Statistics',
          },
          auth: {
            login: 'Sign In',
            register: 'Create Account',
            email: 'Email',
            password: 'Password',
            name: 'Your name',
            forgotPassword: 'Forgot password?',
            noAccount: "Don't have an account?",
            hasAccount: 'Already have an account?',
            signUp: 'Sign up',
            signIn: 'Sign in',
            sendLink: 'Send reset link',
            newPassword: 'New password',
            confirmPassword: 'Confirm password',
            setPassword: 'Set new password',
            checkEmail: 'Check your email for a confirmation link.',
            passwordMismatch: 'Passwords do not match',
            resetSent: 'Reset link sent — check your email.',
            confirmationExpired: 'This link has expired.',
            logout: 'Log out',
            wrongCredentials: 'Incorrect email or password',
            offline: 'No internet connection',
            serverError: 'Server error — please try again',
            resendEmail: 'Resend email',
            resendSent: 'Confirmation email sent',
            resendIn: 'Resend in {{seconds}}s',
          },
          common: {
            loading: 'Loading…',
            error: 'Something went wrong',
            save: 'Save',
            saved: 'Saved',
            cancel: 'Cancel',
            back: 'Back',
            add: 'Add',
            delete: 'Delete',
          },
          settings: {
            logoutConfirmTitle: 'Log out?',
            logoutConfirmMsg: 'Are you sure you want to log out?',
            reorderFailed: "Couldn't save order — please try again",
            account: 'Account',
            editProfile: 'Edit profile',
            changePassword: 'Change password',
            practices: 'Practices',
            myPractices: 'My practices',
            data: 'Data',
            import: 'Import data',
            app: 'App',
            language: 'Language',
            help: 'Help & FAQ',
            saved: 'Changes saved',
            currentPassword: 'Current password',
            subtitle: 'Account & preferences',
          },
          practice: {
            edit: 'Edit practice',
            hide: 'Hide practice',
            show: 'Show practice',
            delete: 'Delete practice',
            deleteConfirm: 'Delete',
            empty: 'No practices yet',
            listSubtitle_one: '{{count}} practice · drag to reorder',
            listSubtitle_other: '{{count}} practices · drag to reorder',
            typeBool: 'Yes / No',
            typeInt: 'Count',
            typeDuration: 'Duration',
            typeTime: 'Time',
            typeText: 'Text',
          },
          today: {
            group: 'Practices',
            filledOf: '{{filled}} of {{total}}',
            requiredLeft_one: '{{count}} required left',
            requiredLeft_other: '{{count}} required left',
            required: 'Required',
            add: '+ Add',
            edit: 'Edit',
            editValue: 'Edit {{name}}',
            addTimeFor: 'Add time to {{name}}',
            done: 'Done',
            clear: 'Clear',
            mode: 'Mode',
            modeAdd: 'Add',
            modeSet: 'Set total',
            logged: 'Logged:',
            newTotal: 'New total',
            addAmount: 'Add {{amount}}',
            setAmount: 'Set {{amount}}',
            keyBackspace: 'Delete digit',
            keyReset: 'Reset',
            savedAsYouType: 'Saved as you type',
            calendar: 'Calendar',
            openCalendar: 'Open calendar',
            prevMonth: 'Previous month',
            nextMonth: 'Next month',
            month: 'Month',
            year: 'Year',
            legendMissing: 'Required practices missing',
            goToday: 'Today',
            unitMin: 'min',
            unitH: 'h',
            more: 'More',
            tabs: 'Main navigation',
            tabLog: 'Log',
            tabInsights: 'Insights',
            tabYatra: 'Yatra',
            tabSettings: 'Settings',
          },
          home: {
            noPractices: 'No practices yet',
            practicesMenu: 'Practices',
            addPractice: 'Add new practice',
            editPractices: 'Edit practices',
            reportsMenu: 'Reports',
            viewYatras: 'View yatras',
            addStarters: 'Add starter practices',
            addCustom: 'or create a custom one',
            addFirst: 'Add your first practice',
            offline: "You're offline — changes will sync when reconnected",
            addMinutes: 'Add minutes',
            addMinutesPlaceholder: 'e.g. 30',
            optional: 'Optional',
            saveFailed: 'Could not save',
            durationHint: 'Enter total minutes (e.g. 90 for 1h 30m)',
            required: 'Required',
            today: 'Today',
            yesterday: 'Yesterday',
            tomorrow: 'Tomorrow',
            nothingLogged: 'Nothing was logged on this day',
          },
          charts: {
            title: 'Charts',
            emptyTitle: 'No reports yet',
            emptySubtitle: 'Create your first report to start tracking trends',
            selectAll: 'Select all',
            clearAll: 'Clear',
            create: 'Create report',
            newReport: 'New report',
            addReport: 'Add new report',
            downloadCsv: 'Download data (CSV)',
            shareLink: 'Share reports link',
            reportName: 'Report name',
            reportNamePlaceholder: 'Report name',
            reportType: 'Report type',
            selectPractices: 'Select practices',
            selectWithType: 'Select practices + type',
            next: 'Next',
            saveReport: 'Save report',
            noPractices: 'No active practices',
            manage: 'Manage reports',
            allPractices: 'All practices',
            duration: 'Duration',
            noData: 'No data',
            share: 'Share',
            copied: 'Copied!',
            download: 'Download',
            date: 'Date',
            kindGraph: 'Graph',
            kindGrid: 'Grid',
            kindGraphDesc: 'Line, bar, dot chart',
            kindGridDesc: 'Table view',
            traceLine: 'Line',
            traceBar: 'Bar',
            traceDot: 'Dot',
            traceCustomLabel: 'Custom label',
            showAverage: 'Avg',
            barLayout: 'Bar layout',
            barLayoutGrouped: 'Grouped',
            barLayoutStacked: 'Stacked',
            barLayoutOverlaid: 'Overlaid',
            addPractice: 'Add practice',
            add: 'Add',
            noPracticesAdded: 'No practices added',
            practiceCount: '{{count}} practices',
            deleteTitle: 'Delete report',
            deleteMsg: 'Delete {{name}}?',
            empty: 'No reports yet',
            yAxis: 'Y-axis',
            yAxisAuto: 'Auto',
            yAxisRight: 'Right axis',
          },
        },
      },
    },
    interpolation: { escapeValue: false },
  })
}

beforeAll(() => server.listen({ onUnhandledRequest: 'warn' }))
afterEach(() => { cleanup(); server.resetHandlers() })
afterAll(() => server.close())
